export const TABELAS = Object.freeze({
  EMPRESA: "TSIEMP",
  CENTRO_RESULTADO: "TSICUS",
  CONTA_CONTABIL: "TCBPLA",
  USUARIO: "Usuario",
  ORC_EMPRESA: "AD_ORCEMP",
  ORC_CENTRO_RESULTADO: "AD_ORCCUS",
  ORC_CONTA: "AD_ORCCTA",
  ORC_USUARIO: "AD_ORCUSU",
  ORC_USUARIO_CENTRO: "AD_ORCUSUCUS",
  ORCAMENTO: "AD_ORCAMENTO",
  ORCAMENTO_MES: "AD_ORCAMENTOMES",
  REALIZADO_MANUAL: "AD_ORCREAL",
  META_CONTABIL: "TCBMET"
});

export const STATUS_ATIVO = Object.freeze({ ativo: "S", inativo: "N" });

export const STATUS_ORCAMENTO = Object.freeze(["RASCUNHO", "ABERTO", "APROVADO", "BLOQUEADO"]);
